//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketOrders
    {
        public int Id { get; set; }
        public Nullable<int> Id_order { get; set; }
        public Nullable<int> Id_ticket { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
