//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.TicketOrders = new HashSet<TicketOrders>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_session { get; set; }
        public Nullable<int> Id_place { get; set; }
        public Nullable<int> Ticket_number { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual Sessions Sessions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketOrders> TicketOrders { get; set; }
    }
}
